[project]
name = "brain"
version = "1.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = { text = "MIT" }
authors = [{ name = "William D'Onofrio" }]
dependencies = []

[project.optional-dependencies]
dev = [
  "black>=24.3.0,<25.0.0",
  "flake8>=6.0.0,<7.0.0",
  "pre-commit>=3.3.3,<4.0.0",
  "pyproject-flake8>=6.0.0.post1,<7.0.0",
  "pytest>=7.0.0,<8.0.0",
]

[dependency-groups]
dev = [
  "black>=24.3.0,<25.0.0",
  "flake8>=6.0.0,<7.0.0",
  "pre-commit>=3.3.3,<4.0.0",
  "pyproject-flake8>=6.0.0.post1,<7.0.0",
  "pytest>=7.0.0,<8.0.0",
]

[project.scripts]
brain = "brain.neuron:main"

[tool.flake8]
max-line-length = 1000

[tool.pytest.ini_options]
pythonpath = [".", "src"]

[tool.hatch.build.targets.wheel]
packages = ["src/brain"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
